// Generated by consensus-tools init.
// Customize this file, then run:
//   consensus-tools tests run --agents 6 --script .consensus/generation.ts

/**
 * This script is intentionally deterministic by default (mockResponse).
 * If you provide OPENAI_API_KEY (or --openai-key), the runner will call OpenAI.
 */
const script = {
  name: 'rx_negation_demo',
  task: {
    title: 'Negation test: prescription advancement',
    desc: 'Tell us why this insulin amount is NOT enough based on patient file, insurance reqs, and doctor notes.',
    input: [
      'We want to negation test prescription advancement for diabetic patients.',
      'Explain why the insulin amount is not enough based on:',
      '- patient file',
      '- insurance info/requirements',
      '- doctor notes',
      '',
      'Patient file: (paste here)',
      '',
      'Insurance info/requirements: (paste here)',
      '',
      'Doctor notes: (paste here)'
    ].join("\n")
  },
  expectedAnswer: 'INSUFFICIENT',
  personas: [],
  getPersonas(count) {
    const n = Math.max(3, Number(count || 3));
    const third = Math.ceil(n / 3);

    const mk = (role, i, systemPrompt, personaRole) => ({
      id: `${role}_${i + 1}`,
      name: `${role.toUpperCase()} Agent ${i + 1}`,
      systemPrompt,
      role: personaRole
    });

    const doctors = Array.from({ length: third }, (_, i) =>
      mk(
        'doctor',
        i,
        'You are a practicing clinician. Be precise. Use only the provided case context. Focus on medical necessity.',
        'accurate'
      )
    );
    const support = Array.from({ length: third }, (_, i) =>
      mk(
        'support',
        i,
        'You are customer support at a pharmacy benefits manager. Focus on process, eligibility, required docs, and next steps.',
        'accurate'
      )
    );
    const insurance = Array.from({ length: n - 2 * third }, (_, i) =>
      mk(
        'insurance',
        i,
        'You are an insurance reviewer. Apply coverage criteria and utilization management rules. Be skeptical and cite requirements.',
        i === (n - 2 * third) - 1 ? 'contrarian' : 'accurate'
      )
    );

    return [...doctors, ...support, ...insurance].slice(0, n);
  },
  buildPrompt(persona, task, expectedAnswer) {
    return {
      system: persona.systemPrompt,
      user: [
        'Return JSON: {"answer": string, "confidence": number, "evidence": string[]}',
        '',
        `TASK: ${task.title}`,
        task.desc ? `DESC: ${task.desc}` : '',
        '',
        `INPUT:\n${task.input}`,
        '',
        `EXPECTED (for negation testing): ${expectedAnswer}`
      ].filter(Boolean).join("\n")
    };
  },
  mockResponse(persona, task, expectedAnswer) {
    const answer = persona.role === "contrarian" ? "SUFFICIENT" : expectedAnswer;
    return JSON.stringify({
      answer,
      confidence: persona.role === "contrarian" ? 0.2 : 0.9,
      evidence: [persona.name, task.title]
    });
  }
};

export default script;
